const val KOTLIN_VERSION = "1.6.0"
const val KTOR_VERSION = "1.6.7"
const val COROUTINES_VERSION = "1.5.2-native-mt"
const val SERIALIZATION_VERSION = "1.3.1"
const val DOKKA_VERSION = "1.6.0"
const val BINARY_COMPAT_VERSION = "0.8.0"
