const val KOTLIN_VERSION = "1.6.20"
const val KTOR_VERSION = "2.0.0"
const val COROUTINES_VERSION = "1.6.1"
const val SERIALIZATION_VERSION = "1.3.2"
const val DOKKA_VERSION = "1.6.10"
const val BINARY_COMPAT_VERSION = "0.8.0"
