name: Deploy

on:
  create:
    branches: [ master ]
  push:
    branches: [ master ]

env:
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - name: Get git tag version
        id: git_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: eskatos/gradle-command-action@v1
        name: Publish Tag
        with:
          arguments: publish -PhostPublishing=true -Pversion=${{ steps.git_tag.outputs.VERSION }}
        if: ${{ startsWith(github.ref, 'refs/tags') }}
      - uses: eskatos/gradle-command-action@v1
        name: Publish SNAPSHOT
        with:
          arguments: publish -PhostPublishing=true
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
