name: Docs

on:
  push:
    tags: [ 'v*' ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - uses: gradle/gradle-build-action@v2
        name: Build Docs
        with:
          arguments: clean dokkaHtmlMultiModule

      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: build/dokka/htmlMultiModule
          SINGLE_COMMIT: true
