name: Js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QBittorrent
        run: |
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt-get update
          sudo apt install qbittorrent-nox
          wget "http://www.legittorrents.info/download.php?id=7f34612e0fac5e7b051b78bdf1060113350ebfe0&f=Big%20Buck%20Bunny%20(1920x1080%20h.264).torrent" -O ~/bbb.torrent
          qbittorrent-nox --webui-port=9090 &
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: jsTest
