name: Native

on:
  push:
    branches: [ main, drew/ci-run-tests ]
  pull_request:
    branches: [ main ]

jobs:
  test-native:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup QBittorrent (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt-get update
          sudo apt install libcurl4-openssl-dev qbittorrent-nox
          curl -sSL "http://www.legittorrents.info/download.php?id=7f34612e0fac5e7b051b78bdf1060113350ebfe0&f=Big%20Buck%20Bunny%20(1920x1080%20h.264).torrent" > ~/bbb.torrent
          qbittorrent-nox --webui-port=9090 &
      - uses: docker-practice/actions-setup-docker@master
        if: ${{ startsWith(matrix.os, 'macos') }}
      #- name: Setup QBittorrent (macOS)
      #  if: ${{ startsWith(matrix.os, 'macos') }}
      #  run: |
      #    curl -sSL "http://www.legittorrents.info/download.php?id=7f34612e0fac5e7b051b78bdf1060113350ebfe0&f=Big%20Buck%20Bunny%20(1920x1080%20h.264).torrent" > ~/bbb.torrent
      #    docker run -d lscr.io/linuxserver/qbittorrent:latest -e WEBUI_PORT=9090
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v3
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - uses: gradle/gradle-build-action@v2
        name: Test Windows Target
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          arguments: win64MainKLibrary
      - uses: gradle/gradle-build-action@v2
        name: Test Apple Targets
        if: ${{ startsWith(matrix.os, 'macos') }}
        with:
          arguments: macosMainKLibrary # iosTest tvosTest watchosX86Test
      - uses: gradle/gradle-build-action@v2
        name: Test Linux Target
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        with:
          arguments: linuxX64Test
      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/tests/**'