name: Publish

on:
  create:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

jobs:
  gradle:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - uses: eskatos/gradle-command-action@v1
        name: Publish (macos)
        with:
          arguments: clean publish
        if: |
          !startsWith(matrix.os, 'windows')
      - name: Publish (windows)
        shell: bash
        run: ./gradlew clean publishWin64PublicationToMavenRepository
        if: |
          startsWith(matrix.os, 'windows')
