name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: check
        uses: tj-actions/changed-files@v39
        with:
          files: |
            .github/workflows/tests.yml
            gradle/libs.versions.toml
            gradle/kotlin-js-store/**
            **/*.kt
            **/*.kts

  tests:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
            %USERPROFILE%\.gradle
            %USERPROFILE%\.konan
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Test Apple Targets
        if: startsWith(matrix.os, 'macos')
        run: ./gradlew macosMainKLibrary # iosTest tvosTest watchosX86Test

      - name: Test Jvm Target
        if: startsWith(matrix.os, 'ubuntu')
        run: ./gradlew jvmMainClasses

      - name: Test Linux Target
        if: startsWith(matrix.os, 'ubuntu')
        run: ./gradlew linuxX64MainKLibrary

      - name: Test Js Targets
        if: startsWith(matrix.os, 'ubuntu')
        run: ./gradlew jsMainClasses

      - name: Test Windows Target
        if: startsWith(matrix.os, 'windows')
        run: ./gradlew win64MainKLibrary

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: client/build/reports/tests/**/**
