name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: check
        uses: tj-actions/changed-files@v23
        with:
          files: |
            .github/workflows/tests.yml
            gradle/libs.versions.toml
            gradle/kotlin-js-store/**
            **/*.kt
            **/*.kts

  tests:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true'
    steps:
      - name: Setup QBittorrent (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt-get update
          sudo apt install libcurl4-openssl-dev qbittorrent-nox
          wget "http://www.legittorrents.info/download.php?id=7f34612e0fac5e7b051b78bdf1060113350ebfe0&f=Big%20Buck%20Bunny%20(1920x1080%20h.264).torrent" -O ~/bbb.torrent
          qbittorrent-nox --webui-port=9090 &

      - name: Setup QBittorrent (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install qbittorrent
      - name: Install cURL (Windows)
        uses: msys2/setup-msys2@v2
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-curl
      - name: Start QBittorrent (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        shell: cmd
        run: >-
          mkdir %APPDATA%\qBittorrent &&
          echo [Preferences] > %APPDATA%\qBittorrent\qBittorrent.ini &&
          echo General\StartMinimized=true >> %APPDATA%\qBittorrent\qBittorrent.ini &&
          echo WebUI\Enabled=true >> %APPDATA%\qBittorrent\qBittorrent.ini &&
          echo WebUI\Port=9090 >> %APPDATA%\qBittorrent\qBittorrent.ini &&
          echo WebUI\MaxAuthenticationFailCount=1000 >> %APPDATA%\qBittorrent\qBittorrent.ini &&
          nssm install qBittorrent "C:\Program Files\qBittorrent\qbittorrent.exe" &&
          nssm start qBittorrent

      - name: Patch Ktor/Curl build issue (https://youtrack.jetbrains.com/issue/KTOR-4307)
        if: ${{ startsWith(matrix.os, 'windows') }}
        shell: cmd
        run: |
          ren "${{ runner.temp }}\msys64\mingw64\lib" lib2
          mkdir "${{ runner.temp }}\msys64\mingw64\lib"
          move "${{ runner.temp }}\msys64\mingw64\lib2\libcurl.a" "${{ runner.temp }}\msys64\mingw64\lib\libcurl.a"
          move "${{ runner.temp }}\msys64\mingw64\lib2\libcurl.dll.a" "${{ runner.temp }}\msys64\mingw64\lib\libcurl.dll.a"

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
            %USERPROFILE%\.gradle
            %USERPROFILE%\.konan
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - uses: gradle/gradle-build-action@v2
        name: Test Apple Targets
        if: startsWith(matrix.os, 'macos')
        with:
          arguments: macosMainKLibrary # iosTest tvosTest watchosX86Test

      - uses: gradle/gradle-build-action@v2
        name: Test Jvm Target
        if: startsWith(matrix.os, 'ubuntu')
        with:
          arguments: jvmTest

      - uses: gradle/gradle-build-action@v2
        name: Test Linux Target
        if: startsWith(matrix.os, 'ubuntu')
        with:
          arguments: linuxX64Test

      - uses: gradle/gradle-build-action@v2
        name: Test Js Targets
        if: startsWith(matrix.os, 'ubuntu')
        with:
          arguments: jsTest

      - uses: gradle/gradle-build-action@v2
        name: Test Windows Target
        if: startsWith(matrix.os, 'windows')
        with:
          arguments: win64Test

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Archive test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: client/build/reports/tests/**/**
